import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/components/Footer";
import { Header } from "src/components/Header";
import { Main } from "src/components/Main";


export default function About({
  count,
  isShow,
  handleClick,
  handleDisplay,
  text,
  array,
  handleAdd,
  handleChange,
}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Main page={"about"} />

      <Footer />
    </div>
  );
}
